<?php

namespace AppBundle\Repository;

/**
 * toastRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class toastRepository extends \Doctrine\ORM\EntityRepository
{
}
